### ISSUE TITLE
Add url to an environment variable for use in later post build steps.

### ISSUE THREAD

**Issue by iamamused** [weiyin/appetize-jenkins-plugin#1]
I'd like to include the URL in chat/messages sent to on successfully builds but there doesn't seem to be a way to easily retrieve it. It would be great if you could also set and environment variable with the url that could be used in later steps.

**Comment by weiyin** [comment]
That sounds very useful. I'll work on it.

**Comment by weiyin** [comment]
Just released version 1.1.0.

**Comment by iamamused** [comment]
thanks!
